Template
pesser/edflow pull request #124
Opened 2019-08-07 14:09 UTC by pesser

- provide unified starting templates for tensorflow and pytorch
- introduces LambdaCheckpointHook for easy and generic saving and restoring
- better imports: `from edflow import PyHookedIterator, ...`, see `edflow/__init__.py`
- update `README.md`: not sexy yet, but more helpful with explicit getting started guide
- extend evaluation pipeline to look only into specified keypath
- add TemplateEvalHook to disable writing output if eval_op returns nothing, i.e. use of eval pipeline is optional in TemplateIterator
- introduces LoggingHook: A minimal logger which only understands `scalars` and `images` but can be easily extended by adding custom `handlers`
- introduces TemplateIterator which provides reasonable defaults for both training and evaluation.

2019-08-07 16:50 UTC, pesser commented
the `test_tf_nn.py` test fails. it fails due to `import scikit-image`. replacing the test with this single line fails as well. The error is `dlopen: Cannot load any more object with static TLS`.
Hard to figure out what's going on https://github.com/scikit-learn/scikit-learn/issues/14485
Removing the `import` statements from `edflow/__init__.py` fixes it, but I really want to simplify the import statements. Also, the test fails on travis ci but not on our machines.

2019-08-08 10:48 UTC, pesser commented
running `python -c "import skimage"` before running the tests fixes the problem. Digging deeper, the problem seems to be `.libs/libgomp-3300acd3.so.1.0.0` shipped with `scikit-image`. It uses static TLS, which it probably should not do https://bugzilla.redhat.com/show_bug.cgi?id=1124987

2019-08-08 13:17 UTC, ArWeHei commented on edflow/eval/pipeline.py
>      Args:
wrong docstring format :(

2019-08-08 13:18 UTC, ArWeHei commented on edflow/hooks/logging_hooks/minimal_logging_hook.py
> +        """Args:
Wrong doctoring format again

2019-08-08 13:19 UTC, ArWeHei requested changes
I believe that the test introduced in #131 should break when this PR is applied. Still, we should start keeping the docstrings consistent.

2019-08-08 14:15 UTC, ArWeHei approved these changes
Looks good to me! 👍

2019-08-08 14:16 UTC, merged